name = "chorus"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "chorus-db"
database_id = "8cad1a22-04c0-43b8-b3ad-0dc4c051d235"

# Scheduled algorithm runs
[triggers]
crons = ["*/5 * * * *"]  # Every 5 minutes
